### ISSUE TITLE
楼主网页被挂马了哎 user/*_ideas.html

### ISSUE THREAD

**Issue by dxkite** [little-game-and-simple-software/idea-show#6]
VB马：

![image](https://user-images.githubusercontent.com/7450707/90235013-2e614580-de53-11ea-901e-dfa32a2d6da6.png)

好老的东西了哎，，，

**Comment by 2439905184** [comment]
我后来手动删除了 是我的电脑有病毒吗

**Comment by dxkite** [comment]
可能是你那次不小心被搞了 😄

**Comment by dxkite** [comment]
gh-pages分支还有，你没处理的样子
